[package]
name = "hoofoobot"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.68"
poise = "0.5.2"
shuttle-poise = "0.25.0"
shuttle-runtime = "0.25.0"
shuttle-secrets = "0.25.0"
tracing = "0.1.37"
tokio = { version = "1.26.0", features = ["rt-multi-thread"] }
redis = { version = "0.23.3", features = ["tokio-native-tls-comp", "tokio-comp"] }
